spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3308/batch_data?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1004
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
---
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      defer-datasource-initialization: false
      datasource:
        initialization-mode: never
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bhjin42@gmail.com
    password: uvrt oabq gqdy isbg
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
---
spring:
  batch:
    job:
      enabled: false