# 사용할 db
spring:
  profiles:
    active: mysql

---
# h2 db 연결
spring:
  config:
    activate:
      on-profile: default

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
# mysql 연결
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3308/batch_data?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1004
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

---
#jpa ??
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


---
# mail sender
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bhjin42@gmail.com
    password: uvrt oabq gqdy isbg
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

---

# job 자동실행 방지
spring:
  batch:
    job:
      enabled: false
