spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/billingwise?useSSL=false&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: root
      password: 1004
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
